### PR TITLE
add DVE-2021-0001 as a separate variant of 2018-0003 

### PR DESCRIPTION
**Pull request by Habbie**

### CODE REVIEW

**Comment by pspacek** [comment]
@Habbie Can you create a new one, possibly as copy-paste from the old one? I think it will be less messy and easier to reference.

**Comment by Habbie** [comment]
Ok, did that, with just some small notes in the old one.

**Review by vcunat — APPROVED** [review]
Sounds OK to me.  The report, I mean.  It's unfortunate that even after years they still can't get the dynamic denials right.

**Comment by vcunat** [comment]
Maybe something around disabling aggressive caching (for those names) could be mentioned in workarounds, but I don't really know the design of other implementations around this.

**Comment by Habbie** [comment]
I don't know if any implementations can disable aggressive NSEC per zone; I know PowerDNS can't, so we tend to recommend NTAs here. I think I'll leave it to operators to interpret.

**Review by pspacek — APPROVED** [review]

**Pull request merged**
