### PR TITLE
Format and DVE allocation

### PR DESCRIPTION
**Pull request by jelu**

### CODE REVIEW

**Review by oerdnj — COMMENTED** [review]
Seems, reasonable. I was also thinking, if we could make a list of violations in a parsable format. Something like:

`Violations: 0x20, qname-min, malformed-packet`

at the end of the DVE?

**Comment by jelu** [comment]
Hmmm, if we can do it without having the manage another registry of violations. Perhaps just `Tags: one, two, three` ?

**Comment by oerdnj** [comment]
`Tags:` sounds fine.

**Comment by oerdnj** [comment]
We don't have to have registry for that. Just a freeform that can be unified by `grep and sed` from time to time...

**Comment by oerdnj** [comment]
I found http://stackoverflow.com/questions/4823468/comments-in-markdown

Comments in markdown, so the form would be: `[tags]: # (tag1, tag2, ...)`

**Comment by jelu** [comment]
GitHub supports `[comment]: <what>` and `[comment]: #what`, they produce no output.

But why not have it clearly visible?

**Comment by oerdnj** [comment]
You are right, they might be clearly visible.

**Review by oerdnj — APPROVED** [review]

**Pull request merged**
