### PR TITLE
add DVE-2019-0001: some auths respond NXDOMAIN for Empty Non-Terminals

### PR DESCRIPTION
**Pull request by Habbie**

### CODE REVIEW

**Comment by pspacek** [comment]
Wondering out loud: Shouldn't it be merged with DVE-2017-0017?

**Comment by vixie** [comment]
DVE-2017-0017 uses words like MUST while referencing fairly recent specifications. i think that the behaviour of answering NXDOMAIN for empty nonterminals was always wrong, and that there's no reading of 1034 that could support such implementations. we should lead with that whenever we put another bank's load balancer on the wall of shame. and, every bank's domain name should get its own turn to be listed. so, i'd prefer that more DVE's look like DVE-2017-0017, since the wrong-behaving domain name is in the title. but i do not think other DVE's should be merged there. we need every customer of these load balancers to feel special.

**Comment by Habbie** [comment]
2017-0017 is about wrongly returning NXDOMAIN for non-empty non-terminals, based on query type. This caused trouble before RFC8020 already.

2019-0001 is about wrongly returning NXDOMAIN for empty non-terminals, regardless of query type, which has become a problem only in resolvers that do RFC8020,

**Comment by Habbie** [comment]
There's a longer list of less interesting offenders in https://github.com/PowerDNS/pdns/issues/8496 but I think it would be good to start with the current content of this PR.

**Review by pspacek — APPROVED** [review]

**Pull request merged**
